### PR TITLE
Inherit page font styles

### PR DESCRIPTION
**Pull request by RoelN**
This PR adds an option to _not_ use custom axes or named instances, but have the page styles/weights be naturally applied:

image

Behaviour is:
- If "Inherit page styles" is selected, no `font-variation-settings` is being injected. The browser will render a variable font based on the original CSS in the page.
- If a named instance is selected, the sliders get set to its matching values, and this instance is applied to all elements from the "ELEMENTS" box.
- If the user tweaks an axis, and the resuling values do not match a named instance, the dropdown will be set to "--Custom axes--"

Since "Custom axes" isn't something you can pick as end user (it's always a result of pulling a slider), this option is disabled from the dropdown. It serves as feedback that you're not inheriting & not applying a named instance.

### CODE REVIEW

**Comment by RoelN** [comment]
Fixes https://github.com/arrowtype/type-x/issues/67

**Comment by arrowtype** [comment]
Nice! I haven’t had the chance to test this yet, but I’m really glad you’ve been able to add this – it will be a very useful default. 

One question on labeling: 

is there a specific reason behind using two hyphens to delineate the choices of `—inherit page styles—` and `—custom axes—`? They definitely help to separate those options from the instance names, but I wonder if slight changes might be helpful. 

At first, I thought that the gray `—custom axes—` option was a header for the instances below it. Potentially, I wonder if square braces might be more semantically clear, as they already have a function of injected clarification/explanation in normal [English] usage. 

So, maybe `[Inherit page styles]` and `[custom]` (probably just as one word) might be more clear? Though, please explain if the dashes have some logic that I might be missing.

**Comment by arrowtype** [comment]
After trying this out, I find it super nice!

Two things:
- I think maybe it would make sense to set "inherit" as the default option for Recursive – currently, it's Sans Linear Regular
- What do you think about square braces?

**Comment by RoelN** [comment]
Also re: Slack conversation, how about this?

It makes "inherit" a separate option, and moved "custom" to the optgroup for the named instances:

image

**Pull request merged**
