### PR TITLE
Reset button design

### PR DESCRIPTION
**Pull request by RoelN**
Should fix https://github.com/arrowtype/type-x/issues/71

image

### CODE REVIEW

**Comment by arrowtype** [comment]
I love it! I think this is a really nice upgrade.

I do think we might be able to make it a bit more clear.

image

Or we could even get a bit more intense to make sure users really want to reset:

image

How intense should we be?

**Comment by arrowtype** [comment]
For now, I've gone with the more-intense reset message. It doesn't hurt people much for it to be intense, but it hopefully means that they are more likely to read it and understand it before resetting their potentially hard work. :)

I have also made the red more vibrant in the light theme to better mesh with the overall styling, and I've adjusted padding in that overrides section so that things align to the overall visual grid a bit better.

image

**Comment by arrowtype** [comment]
I'm loving where this is headed! I think that it's definitely the right direction to do away with the hamburger menu. Users have already expanded the menu, so they shouldn't have to do so twice!

However, I have to admit ... the top bar now feels a bit lop-sided to me. On the one hand, this might be a silly overly-designy feeling to ignore, but on the other hand, it feels like we have really prime space used for (visually) nothing. Probably more important, the latest iteration raises "ignore" and "reset" to the same level of visual prominence as "add font override," when they are actions that users will probably take far less often. 

So, my proposal is to put the "add" button in the very top bar, highlighting it as a primary action, and leading directly to the overrides. At the bottom, we can include "ignore" and "reset," which are more advanced-usage features.

I'm a sucker for hover effects that cue clickability (beyond just type color), so I personally feel that the "add" button should get a little background circle when hovered. But, I could be persuaded if you hate this. :)

image

**Comment by arrowtype** [comment]
In the spirit of using our space wisely to communicate with clarity, we could probably make an extra gain by adding two things to my previous mockup: an "add font" label in the top, plus instance names with the family names (right now it may feel "broken" to first-time users that there is a seemingly-duplicated entry for Recursive).

image

**Comment by RoelN** [comment]
I gave the "Add font" the same rounded corners as the other buttons, and in absense of a darker background color I opted to hove to a lighter color, but other than that this should come very close to the proposed design.

Adding instance names is brilliant — lets create a separate issue so it won't block the reset button design.

**Comment by arrowtype** [comment]
Awesome work; this is looking and feeling really good!

**Three thoughts on design:**

1. I think that possibly, giving the "Ignore" button an ellipse helps to show that it will open further configuration rather than triggering an immediate action (such as ignoring overrides altogether or something similar). It's similar to the "Fallback fonts..." button within overrides. Are you comfortable with the ellipses on "Ignore...", @RoelN?

3. The first time I use the extension after loading it, there is a delay before the overrides show up. Would it be reasonable to add some kind of a loading indicator there, so users know to expect something to populate that space? Otherwise, it is possible/likely users will read the visible options and try to add a font before understanding that some defaults are just about to appear.

3. "Add font" with same rounded corners as other buttons: This is okay, but because the button is in such a prominent placement, the button feels more like a "primary button" when it's taller than the others. Because it would look off to make the taller size entirely pill-shaped, I think matching the overall rounded-rectangle look of the select menus and upload target feels about right. It's a bit like on GitHub, main buttons like "Clone or Download" have a rectangular style, while buttons like "Edit" or "Add reaction" have a tertiary, simpler style. I could go either way on whether "ignore" and "reset" get backgrounds – they have relatively little space, so the background feels a bit less natural there, and your previous solution of just highlighting them in a color felt good for such a space. (I still think the background is good on "delete" within each override, though, because that has more space.)

**And one "bug" we might want to smooth out:**

I've noticed that if I add a new font, "reset" the extension, and then open and activate it again, the page will continue to show the previously-added font, until I refresh the page or adjust some settings in the top override. At first, this makes it seem like the reset only partially worked.

So, perhaps it would be helpful to re-inject the default CSS when the extension is reset? We could alternatively try to refresh the webpage, but I would worry about this disrupting half-filled form submissions, etc (I can't imagine that would be a common issue, but every reset form is infuriating to the person it happens to).

image

image

**Comment by RoelN** [comment]
Quick update!

Ignore now has ellipses (or actually three dots, as that looked better imho!)

The reset bug has been fixed.

Also, some general performance improvements.

Still todo:
- Figure out why the etension is _sometimes_ slow upon first use, and/or show a spinner or something.
- "Add font" styling

**Comment by arrowtype** [comment]
@RoelN could we merge this as-is, and then do those further to-do items in another PR?

I'd love to get this onto the chrome web store, so it's easier to share with non-developers. :) I think it'll be easy enough to update, once it's on there, and it's already a really nice tool – especially with the updates here.

**Pull request merged**
